name             'thirdwave-dotfiles'
maintainer       'Thirdwave, LLC'
maintainer_email 'support@thirdwavellc.com'
license          'Apache 2.0'
description      'Installs/Configures thirdwave-dotfiles'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.0'

depends 'apt'
depends 'build-essential'
depends 'mercurial'
depends 'git'
depends 'htop'
depends 'vim'
depends 'zsh'
